manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: arawasu                         
      url-base: https://github.com/Arawasu
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: hammerbeam-slideshow          #new entry
      remote: arawasu                       #new entry
      revision: main                      #new entry
  self:
    path: config
